insert into sido values ('0', '서울특별시');
insert into sido values ('0', '부산광역시');
insert into sido values ('0', '대구광역시');
insert into sido values ('0', '인천광역시');
insert into sido values ('0', '광주광역시');
insert into sido values ('0', '대전광역시');
insert into sido values ('0', '울산광역시');
insert into sido values ('0', '세종특별자치시');
insert into sido values ('0', '경기도');
insert into sido values ('0', '강원도');
insert into sido values ('0', '충청도');
insert into sido values ('0', '전라도');
insert into sido values ('0', '경상도');
insert into sido values ('0', '제주도');
insert into age values ('0', '20대');
insert into age values ('0', '30대');
insert into age values ('0', '40대');
insert into age values ('0', '50대 이상');
insert into waiting_room values ('0', '1', now(), '6', '파이썬 초보만', '1', '0');
insert into waiting_room values ('0', '1', now(), '6', '오점뭐먹', '2', '0');
insert into waiting_room values ('0', '2', now(), '6', 'Nullpointerexception', '3', '1');
insert into waiting_room values ('0', '4', now(), '6', '이건 4번째 방', '2', '0');
insert into waiting_room values ('0', '3', now(), '6', '집가고싶다', '2', '1');
insert into waiting_room values ('0', '2', now(), '6', 'ⓕⓤⓒⓚ', '2', '0');
insert into waiting_room values ('0', '2', now(), '6', '울산광역시', '2', '1');
insert into waiting_room values ('0', '3', now(), '6', '화났어?', '2', '0');

insert into avatar (image_path, name) values ("액션가면.jpg", "액션가면");
insert into avatar (image_path, name) values ("헐크.jpg", "헐크");
insert into avatar (image_path, name) values ("조커.jpg", "조커");
insert into avatar (image_path, name) values ("지니.jpg", "지니");
insert into avatar (image_path, name) values ("아기조커.jpg", "아기조커");
insert into avatar (image_path, name) values ("햄찌우먼.jpg", "햄찌우먼");
insert into avatar (image_path, name) values ("수박맨.jpg", "수박맨");

insert into user (description, gender, name, profile_image_path, social_id, social_type) values ("testing3", "F", "채윤선", "https://jira.ssafy.com/secure/useravatar?avatarId=10508", "5524137@naver.com", 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ("testing", "M", "정건우", "https://jira.ssafy.com/secure/useravatar?avatarId=10341", "abcxj123@naver.com", 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ("testing2", "M", "이주영", "ss.png", "ssafy2@naver.com", 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ("testing3", "F", "이지나", "ts.png", "ssafy3@naver.com", 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ("testing", "M", "김찬영", "sf.png", "ssafy@naver.com", 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ("testing2", "F", "민경욱", "ss.png", "ssafy2@naver.com", 1);

insert into user (description, gender, name, profile_image_path, social_id, social_type) values ("testing3", "F", "박혜인", "ts.png", "ssafy3@naver.com", 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ("testing", "M", "서요셉", "sf.png", "ssafy@naver.com", 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ("testing2", "F", "이삼성", "ss.png", "ssafy2@naver.com", 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ("testing3", "F", "김윤선", "ts.png", "ssafy3@naver.com", 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ("testing", "M", "박세영", "sf.png", "ssafy@naver.com", 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ("testing2", "M", "제진명", "ss.png", "ssafy2@naver.com", 1);

insert into user (description, gender, name, profile_image_path, social_id, social_type) values ("testing3", "F", "김태희", "ts.png", "ssafy3@naver.com", 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ("testing", "F", "김싸피", "sf.png", "ssafy@naver.com", 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ("testing2", "M", "이싸피", "ss.png", "ssafy2@naver.com", 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ("testing3", "F", "윤은혜", "ts.png", "ssafy3@naver.com", 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ("testing", "M", "차은우", "sf.png", "ssafy@naver.com", 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ("testing2", "M", "엄복동", "ss.png", "ssafy2@naver.com", 1);

insert into user (description, gender, name, profile_image_path, social_id, social_type) values ("testing3", "F", "민희진", "ts.png", "ssafy3@naver.com", 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ("testing", "M", "최민식", "sf.png", "ssafy@naver.com", 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ("testing2", "M", "유재석", "ss.png", "ssafy2@naver.com", 1);
insert into user(description, gender, name, profile_image_path, social_id, social_type) values ('Quisque id justo sit amet sapien dignissim vestibulum.', 'M', 'Esra', 'http://dummyimage.com/182x100.png/ff4444/ffffff', 'eromushkin0@nymag.com', 2);
insert into user(description, gender, name, profile_image_path, social_id, social_type) values ('In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'F', 'Dodie', 'http://dummyimage.com/219x100.png/dddddd/000000', 'dcowely1@census.gov', 2);
insert into user(description, gender, name, profile_image_path, social_id, social_type) values ('Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'F', 'Shelba', 'http://dummyimage.com/233x100.png/dddddd/000000', 'smattecot2@mozilla.com', 2);

insert into user(description, gender, name, profile_image_path, social_id, social_type) values ('In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'M', 'Bartholemy', 'http://dummyimage.com/194x100.png/5fa2dd/ffffff', 'balfonsetti3@so-net.ne.jp', 1);
insert into user(description, gender, name, profile_image_path, social_id, social_type) values ('Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.', 'M', 'Titus', 'http://dummyimage.com/217x100.png/5fa2dd/ffffff', 'tfilipov4@europa.eu', 1);
insert into user(description, gender, name, profile_image_path, social_id, social_type) values ('Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.', 'F', 'Nola', 'http://dummyimage.com/244x100.png/ff4444/ffffff', 'ndaile5@mlb.com', 1);
insert into user(description, gender, name, profile_image_path, social_id, social_type) values ('Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.', 'M', 'Kristo', 'http://dummyimage.com/136x100.png/ff4444/ffffff', 'kwebby6@1und1.de', 2);

insert into user(description, gender, name, profile_image_path, social_id, social_type) values ('Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'M', 'Gerry', 'http://dummyimage.com/177x100.png/cc0000/ffffff', 'ghague7@rakuten.co.jp', 1);
insert into user(description, gender, name, profile_image_path, social_id, social_type) values ('Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'F', 'Ansley', 'http://dummyimage.com/120x100.png/5fa2dd/ffffff', 'ablankenship8@cam.ac.uk', 1);
insert into user(description, gender, name, profile_image_path, social_id, social_type) values ('In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'F', 'Sheri', 'http://dummyimage.com/194x100.png/dddddd/000000', 'soscroft9@diigo.com', 1);
insert into user(description, gender, name, profile_image_path, social_id, social_type) values ('Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. ', 'F', 'Ellie', 'http://dummyimage.com/120x100.png/ff4444/ffffff', 'ebullusa@soup.io', 1);

insert into user(description, gender, name, profile_image_path, social_id, social_type) values ('Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'M', 'Harlen', 'http://dummyimage.com/141x100.png/ff4444/ffffff', 'hgreenhamb@bloglines.com', 2);
insert into user(description, gender, name, profile_image_path, social_id, social_type) values ('Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.', 'F', 'Bella', 'http://dummyimage.com/161x100.png/ff4444/ffffff', 'bassiterc@dropbox.com', 2);

insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Re-contextualized value-added capacity', 'F', 'Beryle', 'http://dummyimage.com/146x100.png/ff4444/ffffff', 'bhuffer0@uiuc.edu', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Compatible context-sensitive support', 'F', 'Augusta', 'http://dummyimage.com/180x100.png/5fa2dd/ffffff', 'amccudden1@gov.uk', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Devolved mission-critical info-mediaries', 'M', 'Barry', 'http://dummyimage.com/101x100.png/cc0000/ffffff', 'bkitchin2@cbc.ca', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Right-sized intermediate system engine', 'M', 'Weston', 'http://dummyimage.com/134x100.png/ff4444/ffffff', 'whaskell3@ft.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Total intermediate architecture', 'F', 'Karna', 'http://dummyimage.com/240x100.png/dddddd/000000', 'kgaitley4@accuweather.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Vision-oriented real-time definition', 'F', 'Colly', 'http://dummyimage.com/217x100.png/5fa2dd/ffffff', 'cdeverille5@wiley.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Reverse-engineered high-level definition', 'F', 'Cordi', 'http://dummyimage.com/189x100.png/ff4444/ffffff', 'carthey6@tumblr.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Pre-emptive 4th generation architecture', 'M', 'Corrie', 'http://dummyimage.com/241x100.png/dddddd/000000', 'crillatt7@a8.net', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Up-sized radical intranet', 'M', 'Major', 'http://dummyimage.com/186x100.png/ff4444/ffffff', 'moakwell8@miitbeian.gov.cn', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Cross-platform modular core', 'M', 'Niven', 'http://dummyimage.com/158x100.png/ff4444/ffffff', 'nhumpage9@fema.gov', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Focused maximized matrices', 'F', 'Nessi', 'http://dummyimage.com/134x100.png/ff4444/ffffff', 'nvaynea@deviantart.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Automated global secured line', 'M', 'Loren', 'http://dummyimage.com/118x100.png/dddddd/000000', 'ldominkab@google.es', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Customizable multi-state project', 'F', 'Lorri', 'http://dummyimage.com/223x100.png/ff4444/ffffff', 'ldegenhardtc@scribd.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Networked analyzing neural-net', 'F', 'Kellsie', 'http://dummyimage.com/242x100.png/5fa2dd/ffffff', 'kantoniazzid@businesswire.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Triple-buffered dedicated protocol', 'M', 'Cesare', 'http://dummyimage.com/185x100.png/ff4444/ffffff', 'cbartaline@phoca.cz', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Inverse national flexibility', 'M', 'Hercule', 'http://dummyimage.com/112x100.png/dddddd/000000', 'hgochf@google.de', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Seamless web-enabled structure', 'F', 'Aleta', 'http://dummyimage.com/191x100.png/cc0000/ffffff', 'alobbeg@cam.ac.uk', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Automated encompassing challenge', 'M', 'Kareem', 'http://dummyimage.com/242x100.png/5fa2dd/ffffff', 'krosenvasserh@auda.org.au', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Managed 4th generation instruction set', 'F', 'Tootsie', 'http://dummyimage.com/211x100.png/5fa2dd/ffffff', 'tbrotheridgei@photobucket.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Team-oriented demand-driven leverage', 'M', 'Ruddie', 'http://dummyimage.com/155x100.png/ff4444/ffffff', 'rbertomieuj@livejournal.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Customizable grid-enabled help-desk', 'M', 'Jeramie', 'http://dummyimage.com/192x100.png/5fa2dd/ffffff', 'jdymondk@upenn.edu', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('User-friendly solution-oriented service-desk', 'M', 'Osbert', 'http://dummyimage.com/142x100.png/5fa2dd/ffffff', 'omazeyl@boston.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Cross-platform even-keeled website', 'M', 'Desi', 'http://dummyimage.com/107x100.png/5fa2dd/ffffff', 'daiersm@deliciousdays.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Cross-group context-sensitive algorithm', 'M', 'Rudyard', 'http://dummyimage.com/217x100.png/cc0000/ffffff', 'rwalthalln@so-net.ne.jp', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Secured contextually-based encryption', 'F', 'Melamie', 'http://dummyimage.com/232x100.png/cc0000/ffffff', 'mstollmeiero@photobucket.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Grass-roots eco-centric functionalities', 'F', 'Rosie', 'http://dummyimage.com/178x100.png/ff4444/ffffff', 'rcornesp@fc2.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Triple-buffered transitional data-warehouse', 'M', 'Patrice', 'http://dummyimage.com/166x100.png/cc0000/ffffff', 'pfaustinq@clickbank.net', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Centralized empowering hub', 'F', 'Lynett', 'http://dummyimage.com/156x100.png/ff4444/ffffff', 'lwyther@bizjournals.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Automated coherent open system', 'F', 'Mureil', 'http://dummyimage.com/218x100.png/cc0000/ffffff', 'mridoutts@alibaba.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Inverse methodical open system', 'M', 'Lorry', 'http://dummyimage.com/172x100.png/cc0000/ffffff', 'lcrusht@unc.edu', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Mandatory logistical algorithm', 'M', 'Kory', 'http://dummyimage.com/134x100.png/5fa2dd/ffffff', 'kvickerstaffu@globo.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Networked methodical methodology', 'M', 'Willey', 'http://dummyimage.com/167x100.png/ff4444/ffffff', 'wmcmakinv@si.edu', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Total even-keeled infrastructure', 'M', 'Kayne', 'http://dummyimage.com/186x100.png/ff4444/ffffff', 'kmcfeatw@wiley.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Grass-roots human-resource initiative', 'F', 'Brinna', 'http://dummyimage.com/232x100.png/cc0000/ffffff', 'brannaldx@yandex.ru', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Open-architected heuristic interface', 'F', 'Juditha', 'http://dummyimage.com/214x100.png/ff4444/ffffff', 'jadrianelloy@arizona.edu', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Secured background matrices', 'M', 'Keene', 'http://dummyimage.com/138x100.png/5fa2dd/ffffff', 'kdinceyz@wix.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Total 4th generation matrices', 'M', 'Ches', 'http://dummyimage.com/231x100.png/cc0000/ffffff', 'charfleet10@godaddy.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Streamlined zero defect methodology', 'M', 'Jonathan', 'http://dummyimage.com/241x100.png/cc0000/ffffff', 'jkilius11@wp.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('User-centric asymmetric adapter', 'F', 'Sephira', 'http://dummyimage.com/228x100.png/ff4444/ffffff', 'sbelliard12@technorati.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Programmable local adapter', 'M', 'Ellerey', 'http://dummyimage.com/234x100.png/cc0000/ffffff', 'eskrine13@goo.ne.jp', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Profit-focused logistical focus group', 'F', 'Evita', 'http://dummyimage.com/200x100.png/dddddd/000000', 'eshilton14@addtoany.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Versatile value-added algorithm', 'M', 'Arnoldo', 'http://dummyimage.com/184x100.png/ff4444/ffffff', 'aguerola15@networksolutions.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Proactive needs-based system engine', 'F', 'Elysha', 'http://dummyimage.com/243x100.png/5fa2dd/ffffff', 'emilmo16@illinois.edu', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('User-friendly discrete complexity', 'F', 'Nora', 'http://dummyimage.com/172x100.png/cc0000/ffffff', 'nbisley17@bloglovin.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Synchronised global application', 'M', 'Boote', 'http://dummyimage.com/192x100.png/cc0000/ffffff', 'bjanauschek18@homestead.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Enterprise-wide next generation focus group', 'M', 'Salmon', 'http://dummyimage.com/155x100.png/ff4444/ffffff', 'spughe19@constantcontact.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Visionary coherent array', 'F', 'Dorian', 'http://dummyimage.com/121x100.png/ff4444/ffffff', 'dlinley1a@mlb.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Assimilated background pricing structure', 'F', 'Shea', 'http://dummyimage.com/180x100.png/dddddd/000000', 'screase1b@scientificamerican.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Networked actuating open architecture', 'M', 'Tripp', 'http://dummyimage.com/108x100.png/ff4444/ffffff', 'tormrod1c@moonfruit.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Self-enabling web-enabled database', 'F', 'Cathryn', 'http://dummyimage.com/233x100.png/ff4444/ffffff', 'cstockport1d@de.vu', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Implemented global task-force', 'M', 'Jamison', 'http://dummyimage.com/249x100.png/dddddd/000000', 'jpreshous1e@meetup.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Realigned reciprocal customer loyalty', 'F', 'Winna', 'http://dummyimage.com/188x100.png/ff4444/ffffff', 'wdarbey1f@latimes.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Automated zero administration standardization', 'F', 'Fina', 'http://dummyimage.com/149x100.png/ff4444/ffffff', 'fbroxholme1g@bravesites.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Reverse-engineered mobile functionalities', 'F', 'Tish', 'http://dummyimage.com/102x100.png/5fa2dd/ffffff', 'trivers1h@csmonitor.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Triple-buffered modular circuit', 'F', 'Nanette', 'http://dummyimage.com/182x100.png/ff4444/ffffff', 'nrider1i@mapquest.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Total national protocol', 'M', 'Reamonn', 'http://dummyimage.com/112x100.png/5fa2dd/ffffff', 'relsbury1j@csmonitor.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Switchable 6th generation service-desk', 'F', 'Fedora', 'http://dummyimage.com/211x100.png/cc0000/ffffff', 'fdohr1k@huffingtonpost.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Multi-lateral bottom-line architecture', 'F', 'Chelsea', 'http://dummyimage.com/191x100.png/cc0000/ffffff', 'cmargarson1l@utexas.edu', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Cross-group 4th generation analyzer', 'F', 'Cybill', 'http://dummyimage.com/110x100.png/ff4444/ffffff', 'cmolyneaux1m@netlog.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Multi-lateral mobile throughput', 'F', 'Anitra', 'http://dummyimage.com/205x100.png/dddddd/000000', 'astatter1n@hhs.gov', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Assimilated leading edge neural-net', 'M', 'Trip', 'http://dummyimage.com/217x100.png/cc0000/ffffff', 'tyellep1o@globo.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Synergized neutral software', 'F', 'Angela', 'http://dummyimage.com/109x100.png/5fa2dd/ffffff', 'acleverley1p@europa.eu', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Centralized clear-thinking matrix', 'M', 'Aguistin', 'http://dummyimage.com/224x100.png/ff4444/ffffff', 'ajan1q@senate.gov', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Fully-configurable zero defect extranet', 'F', 'Kala', 'http://dummyimage.com/230x100.png/ff4444/ffffff', 'kgordge1r@earthlink.net', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Synergized leading edge matrices', 'M', 'Gaven', 'http://dummyimage.com/153x100.png/dddddd/000000', 'gbarnardo1s@wordpress.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Intuitive reciprocal focus group', 'F', 'Dorthy', 'http://dummyimage.com/220x100.png/5fa2dd/ffffff', 'dwallbanks1t@google.fr', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Secured background algorithm', 'F', 'Lynea', 'http://dummyimage.com/207x100.png/5fa2dd/ffffff', 'lmcgrath1u@geocities.jp', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Up-sized dynamic secured line', 'M', 'Butch', 'http://dummyimage.com/239x100.png/5fa2dd/ffffff', 'bfenck1v@mapquest.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Persistent hybrid capacity', 'M', 'Reed', 'http://dummyimage.com/140x100.png/cc0000/ffffff', 'rtresler1w@china.com.cn', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Multi-layered interactive hardware', 'F', 'Roselia', 'http://dummyimage.com/132x100.png/5fa2dd/ffffff', 'rcartmail1x@ftc.gov', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Multi-tiered methodical alliance', 'M', 'Payton', 'http://dummyimage.com/159x100.png/5fa2dd/ffffff', 'pguerin1y@aboutads.info', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Visionary 24 hour definition', 'M', 'Abdul', 'http://dummyimage.com/198x100.png/dddddd/000000', 'amillam1z@networkadvertising.org', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Universal uniform open system', 'M', 'Kippar', 'http://dummyimage.com/169x100.png/dddddd/000000', 'kbushell20@businessinsider.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Switchable next generation application', 'F', 'Rosanna', 'http://dummyimage.com/176x100.png/5fa2dd/ffffff', 'rpaulus21@google.ru', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Devolved dedicated software', 'F', 'Elvira', 'http://dummyimage.com/183x100.png/dddddd/000000', 'enystrom22@intel.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Open-architected context-sensitive architecture', 'M', 'Abby', 'http://dummyimage.com/119x100.png/cc0000/ffffff', 'aovise23@princeton.edu', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Pre-emptive systematic paradigm', 'M', 'Reinwald', 'http://dummyimage.com/151x100.png/5fa2dd/ffffff', 'rferryn24@gravatar.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Reactive stable support', 'F', 'Calli', 'http://dummyimage.com/224x100.png/5fa2dd/ffffff', 'cmauro25@google.ru', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Enterprise-wide bifurcated interface', 'F', 'Gae', 'http://dummyimage.com/228x100.png/dddddd/000000', 'gbrager26@bbb.org', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Vision-oriented neutral groupware', 'F', 'Chery', 'http://dummyimage.com/214x100.png/cc0000/ffffff', 'csteffan27@jiathis.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Persevering bifurcated success', 'F', 'Beitris', 'http://dummyimage.com/174x100.png/5fa2dd/ffffff', 'bbill28@yellowpages.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Reverse-engineered well-modulated internet solution', 'F', 'Andriette', 'http://dummyimage.com/121x100.png/dddddd/000000', 'amckellen29@sitemeter.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Organic full-range service-desk', 'F', 'Cindra', 'http://dummyimage.com/246x100.png/dddddd/000000', 'cdavion2a@themeforest.net', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Reverse-engineered 6th generation intranet', 'M', 'Ernesto', 'http://dummyimage.com/235x100.png/5fa2dd/ffffff', 'ebeauchop2b@miibeian.gov.cn', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Diverse high-level benchmark', 'F', 'Gayla', 'http://dummyimage.com/240x100.png/ff4444/ffffff', 'gisakovitch2c@parallels.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Open-source system-worthy infrastructure', 'F', 'Amie', 'http://dummyimage.com/216x100.png/cc0000/ffffff', 'acumberledge2d@tamu.edu', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Object-based disintermediate success', 'M', 'Brewster', 'http://dummyimage.com/209x100.png/ff4444/ffffff', 'bavieson2e@amazon.co.uk', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Multi-layered zero defect analyzer', 'F', 'Mady', 'http://dummyimage.com/178x100.png/cc0000/ffffff', 'mnestor2f@jugem.jp', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Phased bi-directional firmware', 'F', 'Joey', 'http://dummyimage.com/207x100.png/ff4444/ffffff', 'jpipe2g@ifeng.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Reactive background Graphic Interface', 'F', 'Birgit', 'http://dummyimage.com/217x100.png/ff4444/ffffff', 'bcarrabott2h@bloglines.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Enterprise-wide asymmetric hardware', 'F', 'Olympe', 'http://dummyimage.com/108x100.png/dddddd/000000', 'ocaze2i@msu.edu', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Managed next generation portal', 'M', 'Barris', 'http://dummyimage.com/121x100.png/cc0000/ffffff', 'bockland2j@europa.eu', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Re-engineered executive interface', 'F', 'Tina', 'http://dummyimage.com/117x100.png/dddddd/000000', 'tpilipyak2k@shutterfly.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Optional local benchmark', 'F', 'Katherine', 'http://dummyimage.com/129x100.png/dddddd/000000', 'kcrowhurst2l@example.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Pre-emptive full-range attitude', 'M', 'Vasilis', 'http://dummyimage.com/168x100.png/5fa2dd/ffffff', 'vbeeck2m@discuz.net', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Synchronised bifurcated initiative', 'M', 'Ian', 'http://dummyimage.com/152x100.png/5fa2dd/ffffff', 'itaillant2n@histats.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Expanded didactic portal', 'F', 'Harri', 'http://dummyimage.com/159x100.png/dddddd/000000', 'hpretorius2o@so-net.ne.jp', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Expanded dedicated software', 'M', 'Eric', 'http://dummyimage.com/138x100.png/dddddd/000000', 'echrystie2p@unblog.fr', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Diverse methodical product', 'M', 'Gardie', 'http://dummyimage.com/230x100.png/5fa2dd/ffffff', 'gfinden2q@foxnews.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('User-friendly directional capability', 'F', 'Dora', 'http://dummyimage.com/162x100.png/ff4444/ffffff', 'dmachan2r@mapy.cz', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Automated zero defect synergy', 'F', 'Veronika', 'http://dummyimage.com/159x100.png/ff4444/ffffff', 'vquarmby2s@artisteer.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Balanced needs-based system engine', 'F', 'Nettie', 'http://dummyimage.com/109x100.png/dddddd/000000', 'nyeatman2t@php.net', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Self-enabling actuating benchmark', 'M', 'Jock', 'http://dummyimage.com/109x100.png/5fa2dd/ffffff', 'jzarfai2u@npr.org', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Reactive attitude-oriented paradigm', 'M', 'Yorke', 'http://dummyimage.com/217x100.png/ff4444/ffffff', 'ylucio2v@comcast.net', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Pre-emptive cohesive array', 'F', 'Luce', 'http://dummyimage.com/120x100.png/ff4444/ffffff', 'lavrasin2w@ow.ly', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Operative mission-critical matrix', 'M', 'Clerkclaud', 'http://dummyimage.com/169x100.png/dddddd/000000', 'cmusson2x@wp.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Streamlined uniform challenge', 'F', 'Nancy', 'http://dummyimage.com/238x100.png/ff4444/ffffff', 'nsouthall2y@amazon.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Operative maximized capability', 'M', 'Calvin', 'http://dummyimage.com/156x100.png/ff4444/ffffff', 'chamor2z@bbb.org', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Integrated stable success', 'F', 'Justina', 'http://dummyimage.com/136x100.png/5fa2dd/ffffff', 'jallerton30@google.com.hk', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Operative multi-state success', 'F', 'Irena', 'http://dummyimage.com/152x100.png/5fa2dd/ffffff', 'iillem31@delicious.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('User-centric human-resource middleware', 'F', 'Lonna', 'http://dummyimage.com/142x100.png/cc0000/ffffff', 'lmora32@nba.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Fundamental holistic focus group', 'F', 'Benoite', 'http://dummyimage.com/165x100.png/dddddd/000000', 'blattimore33@ted.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Reverse-engineered web-enabled open system', 'F', 'Eirena', 'http://dummyimage.com/164x100.png/5fa2dd/ffffff', 'evannucci34@thetimes.co.uk', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Extended stable function', 'F', 'Arlina', 'http://dummyimage.com/180x100.png/dddddd/000000', 'adurbyn35@umich.edu', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Streamlined well-modulated knowledge base', 'M', 'Davey', 'http://dummyimage.com/112x100.png/dddddd/000000', 'dbeeres36@upenn.edu', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Exclusive static functionalities', 'M', 'Sylvester', 'http://dummyimage.com/238x100.png/dddddd/000000', 'sscouller37@apple.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Synergized bi-directional concept', 'M', 'Dom', 'http://dummyimage.com/240x100.png/cc0000/ffffff', 'ddragon38@storify.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Innovative coherent secured line', 'M', 'Ricardo', 'http://dummyimage.com/247x100.png/5fa2dd/ffffff', 'rdayes3a@altervista.org', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Organic explicit attitude', 'M', 'Tyrus', 'http://dummyimage.com/114x100.png/dddddd/000000', 'tlacer3b@shinystat.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Proactive regional hierarchy', 'F', 'Ediva', 'http://dummyimage.com/241x100.png/dddddd/000000', 'ewragg3c@dot.gov', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Monitored client-server challenge', 'F', 'Dinah', 'http://dummyimage.com/225x100.png/cc0000/ffffff', 'dlowings3d@bbb.org', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Reverse-engineered clear-thinking forecast', 'F', 'Maggy', 'http://dummyimage.com/148x100.png/cc0000/ffffff', 'mdoelle3e@wikipedia.org', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Fully-configurable context-sensitive benchmark', 'F', 'Tawsha', 'http://dummyimage.com/155x100.png/dddddd/000000', 'tmackean3f@patch.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Reverse-engineered bi-directional open system', 'F', 'Marla', 'http://dummyimage.com/125x100.png/cc0000/ffffff', 'mbrugger3g@kickstarter.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Balanced heuristic task-force', 'M', 'Leonerd', 'http://dummyimage.com/104x100.png/cc0000/ffffff', 'lattril3h@prnewswire.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Networked maximized throughput', 'M', 'Fletch', 'http://dummyimage.com/197x100.png/5fa2dd/ffffff', 'fperrelli3j@reuters.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Synergized multimedia focus group', 'F', 'Kendra', 'http://dummyimage.com/164x100.png/dddddd/000000', 'kbrugden3k@ycombinator.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Persistent client-driven algorithm', 'F', 'Nonah', 'http://dummyimage.com/173x100.png/5fa2dd/ffffff', 'nkedge3l@ft.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Persistent well-modulated groupware', 'M', 'Devy', 'http://dummyimage.com/234x100.png/cc0000/ffffff', 'demmens3m@huffingtonpost.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Universal zero tolerance access', 'M', 'Garald', 'http://dummyimage.com/158x100.png/5fa2dd/ffffff', 'gweatherburn3n@about.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Assimilated mobile Graphic Interface', 'M', 'Aksel', 'http://dummyimage.com/111x100.png/cc0000/ffffff', 'alumox3o@ucoz.ru', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Automated regional approach', 'M', 'Sherlocke', 'http://dummyimage.com/189x100.png/dddddd/000000', 'sscopes3p@ocn.ne.jp', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Future-proofed homogeneous help-desk', 'M', 'Joel', 'http://dummyimage.com/194x100.png/5fa2dd/ffffff', 'jnewport3q@dot.gov', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Cross-platform multi-state migration', 'M', 'Kimbell', 'http://dummyimage.com/237x100.png/ff4444/ffffff', 'kmaggiore3r@admin.ch', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Triple-buffered executive open architecture', 'M', 'Rowan', 'http://dummyimage.com/187x100.png/5fa2dd/ffffff', 'rcadney3s@abc.net.au', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Universal static initiative', 'F', 'Bettye', 'http://dummyimage.com/175x100.png/5fa2dd/ffffff', 'bwainscoat3t@amazon.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Multi-channelled stable model', 'M', 'Wallace', 'http://dummyimage.com/172x100.png/dddddd/000000', 'wsimondson3u@google.de', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Pre-emptive multi-state process improvement', 'M', 'Onfroi', 'http://dummyimage.com/184x100.png/dddddd/000000', 'ocollison3v@webs.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Triple-buffered intangible parallelism', 'F', 'Genovera', 'http://dummyimage.com/162x100.png/dddddd/000000', 'gsomerfield3w@shop-pro.jp', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Reverse-engineered explicit moratorium', 'M', 'Saleem', 'http://dummyimage.com/118x100.png/dddddd/000000', 'smarlen3x@imageshack.us', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Realigned multi-state frame', 'F', 'Ellyn', 'http://dummyimage.com/178x100.png/ff4444/ffffff', 'emetschke3y@prweb.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Triple-buffered user-facing budgetary management', 'M', 'Kevan', 'http://dummyimage.com/237x100.png/ff4444/ffffff', 'kmcguirk3z@blogs.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Ergonomic maximized success', 'M', 'Rafael', 'http://dummyimage.com/196x100.png/dddddd/000000', 'rwetton40@sphinn.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Reactive discrete focus group', 'M', 'Buckie', 'http://dummyimage.com/129x100.png/dddddd/000000', 'bheffer41@omniture.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Pre-emptive scalable customer loyalty', 'M', 'Layton', 'http://dummyimage.com/214x100.png/dddddd/000000', 'lkilbey42@gmpg.org', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Synergized exuding intranet', 'F', 'Carry', 'http://dummyimage.com/111x100.png/dddddd/000000', 'cbessant43@weebly.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Customizable responsive capability', 'F', 'Rosanne', 'http://dummyimage.com/217x100.png/5fa2dd/ffffff', 'rmayers44@statcounter.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Enhanced solution-oriented knowledge base', 'M', 'Sean', 'http://dummyimage.com/201x100.png/dddddd/000000', 'shuggons45@microsoft.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Innovative web-enabled intranet', 'M', 'Pat', 'http://dummyimage.com/240x100.png/5fa2dd/ffffff', 'pmiranda46@cisco.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Adaptive explicit support', 'M', 'Michale', 'http://dummyimage.com/169x100.png/dddddd/000000', 'mfranciotti47@vk.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Total client-driven policy', 'F', 'Ruth', 'http://dummyimage.com/152x100.png/dddddd/000000', 'rshayler48@redcross.org', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Managed scalable algorithm', 'F', 'Seline', 'http://dummyimage.com/136x100.png/cc0000/ffffff', 'snares49@mashable.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Team-oriented non-volatile help-desk', 'M', 'Benjy', 'http://dummyimage.com/157x100.png/cc0000/ffffff', 'blatchford4a@fotki.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Pre-emptive 24 hour matrix', 'F', 'Geralda', 'http://dummyimage.com/131x100.png/cc0000/ffffff', 'gbiggen4b@odnoklassniki.ru', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Managed motivating installation', 'F', 'Dotty', 'http://dummyimage.com/208x100.png/ff4444/ffffff', 'dvlach4c@over-blog.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Re-contextualized neutral challenge', 'M', 'Clywd', 'http://dummyimage.com/170x100.png/dddddd/000000', 'cellerton4d@list-manage.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Focused empowering pricing structure', 'F', 'Carolin', 'http://dummyimage.com/155x100.png/cc0000/ffffff', 'cpennoni4e@mashable.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Visionary user-facing synergy', 'M', 'Woody', 'http://dummyimage.com/146x100.png/ff4444/ffffff', 'whadleigh4f@nbcnews.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Horizontal motivating moratorium', 'M', 'Vito', 'http://dummyimage.com/205x100.png/5fa2dd/ffffff', 'vkobel4g@qq.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Public-key high-level throughput', 'F', 'Imogene', 'http://dummyimage.com/122x100.png/dddddd/000000', 'iswann4h@weebly.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Persistent eco-centric help-desk', 'M', 'Whitaker', 'http://dummyimage.com/145x100.png/cc0000/ffffff', 'wgentry4i@cdbaby.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Grass-roots 4th generation workforce', 'M', 'Trent', 'http://dummyimage.com/247x100.png/cc0000/ffffff', 'tbrittain4j@prlog.org', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Synchronised stable standardization', 'F', 'Noni', 'http://dummyimage.com/201x100.png/dddddd/000000', 'nedgeler4k@princeton.edu', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Proactive fresh-thinking adapter', 'F', 'Renee', 'http://dummyimage.com/240x100.png/cc0000/ffffff', 'rmattiacci4l@ftc.gov', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Up-sized cohesive forecast', 'M', 'Bart', 'http://dummyimage.com/122x100.png/ff4444/ffffff', 'bcaulliere4m@auda.org.au', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Customizable demand-driven access', 'F', 'Tricia', 'http://dummyimage.com/167x100.png/ff4444/ffffff', 'tpaull4n@vkontakte.ru', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Multi-layered attitude-oriented ability', 'M', 'Tiebout', 'http://dummyimage.com/219x100.png/dddddd/000000', 'tjeannequin4o@europa.eu', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Profit-focused value-added instruction set', 'M', 'Lemar', 'http://dummyimage.com/119x100.png/cc0000/ffffff', 'lwreiford4p@merriam-webster.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Proactive composite frame', 'M', 'Odo', 'http://dummyimage.com/124x100.png/dddddd/000000', 'ocroizier4q@icq.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Re-contextualized asymmetric ability', 'M', 'Stanleigh', 'http://dummyimage.com/236x100.png/ff4444/ffffff', 'sgelland4r@prnewswire.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Compatible stable structure', 'M', 'Clemens', 'http://dummyimage.com/245x100.png/5fa2dd/ffffff', 'cborrott4s@nbcnews.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Secured discrete archive', 'M', 'Benito', 'http://dummyimage.com/170x100.png/5fa2dd/ffffff', 'bberridge4t@myspace.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Automated multi-tasking help-desk', 'M', 'Fidelio', 'http://dummyimage.com/165x100.png/5fa2dd/ffffff', 'fplumbridge4u@oakley.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Networked uniform process improvement', 'M', 'Kort', 'http://dummyimage.com/122x100.png/dddddd/000000', 'krustedge4v@parallels.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Business-focused fault-tolerant utilisation', 'F', 'Margarete', 'http://dummyimage.com/218x100.png/cc0000/ffffff', 'mboydon4w@fotki.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Integrated optimal system engine', 'F', 'Danita', 'http://dummyimage.com/129x100.png/ff4444/ffffff', 'dmatevosian4x@ftc.gov', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Re-contextualized impactful time-frame', 'F', 'Marylynne', 'http://dummyimage.com/222x100.png/dddddd/000000', 'mstutter4y@fc2.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Down-sized client-driven algorithm', 'F', 'Nertie', 'http://dummyimage.com/182x100.png/cc0000/ffffff', 'nfittall4z@mozilla.org', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Reduced human-resource focus group', 'F', 'Drona', 'http://dummyimage.com/208x100.png/cc0000/ffffff', 'dbohler50@digg.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Versatile stable workforce', 'M', 'Lyman', 'http://dummyimage.com/228x100.png/ff4444/ffffff', 'lealles51@omniture.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Sharable interactive customer loyalty', 'M', 'Emery', 'http://dummyimage.com/248x100.png/5fa2dd/ffffff', 'emisson52@ow.ly', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Synchronised intermediate throughput', 'M', 'Raviv', 'http://dummyimage.com/166x100.png/dddddd/000000', 'rtalman53@miibeian.gov.cn', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Business-focused eco-centric access', 'F', 'Katina', 'http://dummyimage.com/123x100.png/cc0000/ffffff', 'klomas54@ca.gov', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Multi-channelled demand-driven ability', 'F', 'Deerdre', 'http://dummyimage.com/159x100.png/cc0000/ffffff', 'dbrixey55@europa.eu', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Switchable incremental implementation', 'F', 'Gena', 'http://dummyimage.com/166x100.png/ff4444/ffffff', 'ggheerhaert56@prlog.org', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Synchronised logistical local area network', 'M', 'Morse', 'http://dummyimage.com/104x100.png/cc0000/ffffff', 'mivanichev57@exblog.jp', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Devolved stable functionalities', 'F', 'Querida', 'http://dummyimage.com/119x100.png/dddddd/000000', 'qwoolmington58@who.int', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Profit-focused fresh-thinking emulation', 'F', 'Di', 'http://dummyimage.com/219x100.png/5fa2dd/ffffff', 'dblitz59@senate.gov', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Cross-platform systematic contingency', 'M', 'Washington', 'http://dummyimage.com/173x100.png/ff4444/ffffff', 'waumerle5a@flavors.me', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Up-sized local algorithm', 'F', 'Adelle', 'http://dummyimage.com/220x100.png/cc0000/ffffff', 'aknoton5b@twitpic.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Horizontal heuristic capability', 'M', 'Brooks', 'http://dummyimage.com/238x100.png/dddddd/000000', 'bbrookton5c@disqus.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Operative demand-driven matrix', 'M', 'Farrel', 'http://dummyimage.com/157x100.png/cc0000/ffffff', 'fscolland5d@last.fm', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Profound encompassing ability', 'M', 'Huntlee', 'http://dummyimage.com/228x100.png/ff4444/ffffff', 'hsam5e@elegantthemes.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Multi-lateral holistic support', 'F', 'Karine', 'http://dummyimage.com/160x100.png/cc0000/ffffff', 'kgaddas5f@mediafire.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Open-source modular encoding', 'M', 'Alister', 'http://dummyimage.com/195x100.png/5fa2dd/ffffff', 'abellard5g@amazon.co.uk', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Managed cohesive structure', 'F', 'Traci', 'http://dummyimage.com/218x100.png/ff4444/ffffff', 'tclaringbold5h@soundcloud.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Advanced coherent help-desk', 'F', 'Gabbie', 'http://dummyimage.com/199x100.png/dddddd/000000', 'gbenko5i@spiegel.de', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Front-line real-time synergy', 'F', 'Marena', 'http://dummyimage.com/139x100.png/dddddd/000000', 'mlorente5j@pcworld.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Operative actuating adapter', 'F', 'Stephannie', 'http://dummyimage.com/175x100.png/5fa2dd/ffffff', 'slevitt5k@reuters.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Vision-oriented contextually-based circuit', 'M', 'Bryon', 'http://dummyimage.com/170x100.png/ff4444/ffffff', 'bsandercroft5l@apache.org', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Diverse analyzing algorithm', 'F', 'Hildagard', 'http://dummyimage.com/143x100.png/ff4444/ffffff', 'hmargaritelli5m@merriam-webster.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Ameliorated actuating capacity', 'F', 'Cheri', 'http://dummyimage.com/166x100.png/5fa2dd/ffffff', 'cbullene5n@yale.edu', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('User-friendly foreground Graphic Interface', 'M', 'Udell', 'http://dummyimage.com/175x100.png/dddddd/000000', 'uhoodless5o@examiner.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Front-line maximized knowledge base', 'F', 'Lucita', 'http://dummyimage.com/135x100.png/cc0000/ffffff', 'llathee5p@cdbaby.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Programmable static infrastructure', 'M', 'Stanfield', 'http://dummyimage.com/102x100.png/dddddd/000000', 'sniven5q@360.cn', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Persistent contextually-based firmware', 'F', 'Romonda', 'http://dummyimage.com/242x100.png/ff4444/ffffff', 'rvonhindenburg5r@amazon.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Down-sized bandwidth-monitored software', 'F', 'Cordula', 'http://dummyimage.com/190x100.png/cc0000/ffffff', 'cdehooge5s@google.nl', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Public-key exuding knowledge user', 'F', 'Maryjane', 'http://dummyimage.com/234x100.png/dddddd/000000', 'mbuss5t@hc360.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Up-sized maximized monitoring', 'M', 'Dorey', 'http://dummyimage.com/181x100.png/ff4444/ffffff', 'dabelson5u@scribd.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Enterprise-wide bottom-line initiative', 'M', 'Tomkin', 'http://dummyimage.com/166x100.png/ff4444/ffffff', 'tbest5v@flavors.me', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Robust next generation utilisation', 'F', 'Minna', 'http://dummyimage.com/206x100.png/5fa2dd/ffffff', 'mswyer5w@whitehouse.gov', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Horizontal grid-enabled initiative', 'F', 'Tova', 'http://dummyimage.com/106x100.png/dddddd/000000', 'tdriscoll5x@google.pl', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Ameliorated national Graphical User Interface', 'F', 'Willetta', 'http://dummyimage.com/192x100.png/5fa2dd/ffffff', 'wvell5y@who.int', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Profit-focused demand-driven structure', 'F', 'Ethelin', 'http://dummyimage.com/177x100.png/5fa2dd/ffffff', 'emarty5z@webeden.co.uk', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Optional client-driven help-desk', 'F', 'Kirsti', 'http://dummyimage.com/192x100.png/cc0000/ffffff', 'khorley60@cyberchimps.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Synergistic directional budgetary management', 'M', 'Dietrich', 'http://dummyimage.com/176x100.png/dddddd/000000', 'dbartolomieu61@ucla.edu', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Digitized empowering software', 'F', 'Jerry', 'http://dummyimage.com/223x100.png/ff4444/ffffff', 'jromer62@uiuc.edu', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Programmable modular portal', 'M', 'Nathan', 'http://dummyimage.com/171x100.png/5fa2dd/ffffff', 'nrowntree63@wsj.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Re-engineered leading edge toolset', 'F', 'Chere', 'http://dummyimage.com/144x100.png/ff4444/ffffff', 'cruspine64@facebook.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Assimilated high-level approach', 'M', 'Pascal', 'http://dummyimage.com/170x100.png/ff4444/ffffff', 'psymes65@ameblo.jp', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Programmable leading edge encoding', 'M', 'Jard', 'http://dummyimage.com/108x100.png/ff4444/ffffff', 'jsenechell66@economist.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Profound cohesive challenge', 'M', 'Thurston', 'http://dummyimage.com/186x100.png/5fa2dd/ffffff', 'tdunthorn67@apple.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Progressive asynchronous project', 'F', 'Aline', 'http://dummyimage.com/151x100.png/ff4444/ffffff', 'aspellesy68@jugem.jp', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Reverse-engineered global hub', 'M', 'Gunther', 'http://dummyimage.com/168x100.png/dddddd/000000', 'gyacobsohn69@topsy.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Switchable composite installation', 'M', 'Lorin', 'http://dummyimage.com/246x100.png/cc0000/ffffff', 'lwingar6a@whitehouse.gov', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Digitized uniform utilisation', 'M', 'Culver', 'http://dummyimage.com/204x100.png/5fa2dd/ffffff', 'cluetchford6b@meetup.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Vision-oriented global emulation', 'F', 'Hilda', 'http://dummyimage.com/114x100.png/cc0000/ffffff', 'hpecha6c@cpanel.net', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Team-oriented mission-critical info-mediaries', 'M', 'Morgun', 'http://dummyimage.com/224x100.png/ff4444/ffffff', 'minman6d@storify.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Visionary eco-centric open architecture', 'M', 'Winslow', 'http://dummyimage.com/200x100.png/dddddd/000000', 'wcaldron6e@ow.ly', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Sharable zero defect complexity', 'M', 'Haley', 'http://dummyimage.com/171x100.png/ff4444/ffffff', 'hmabbot6f@sohu.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Diverse bifurcated orchestration', 'M', 'Patrizio', 'http://dummyimage.com/210x100.png/dddddd/000000', 'plarkin6g@yellowpages.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Persistent real-time matrix', 'F', 'Lenka', 'http://dummyimage.com/178x100.png/5fa2dd/ffffff', 'ldehaven6h@jimdo.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Seamless user-facing conglomeration', 'F', 'Sayre', 'http://dummyimage.com/130x100.png/5fa2dd/ffffff', 'smanntschke6i@gov.uk', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Networked cohesive hub', 'F', 'Karoline', 'http://dummyimage.com/126x100.png/cc0000/ffffff', 'kveeler6j@edublogs.org', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Inverse zero administration infrastructure', 'M', 'Dunstan', 'http://dummyimage.com/219x100.png/dddddd/000000', 'dlocke6k@nasa.gov', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Managed 4th generation parallelism', 'M', 'Lindsey', 'http://dummyimage.com/150x100.png/5fa2dd/ffffff', 'lgosby6l@mac.com', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Digitized attitude-oriented matrices', 'F', 'Cathrin', 'http://dummyimage.com/243x100.png/5fa2dd/ffffff', 'cpincked6m@sitemeter.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Organic well-modulated capacity', 'F', 'Lilias', 'http://dummyimage.com/197x100.png/cc0000/ffffff', 'lzorzi6n@mail.ru', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Secured demand-driven process improvement', 'F', 'Cecile', 'http://dummyimage.com/210x100.png/dddddd/000000', 'cethelstone6o@fc2.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Distributed tangible implementation', 'M', 'Niel', 'http://dummyimage.com/250x100.png/dddddd/000000', 'ncorrao6p@drupal.org', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Multi-layered clear-thinking local area network', 'M', 'Zaccaria', 'http://dummyimage.com/130x100.png/cc0000/ffffff', 'zdibdin6q@unesco.org', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Automated contextually-based artificial intelligence', 'F', 'Ferdinande', 'http://dummyimage.com/187x100.png/cc0000/ffffff', 'fsille6r@g.co', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Reverse-engineered hybrid hardware', 'M', 'Base', 'http://dummyimage.com/131x100.png/cc0000/ffffff', 'bgosforth6s@answers.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Polarised empowering portal', 'F', 'Amabel', 'http://dummyimage.com/190x100.png/ff4444/ffffff', 'ascammell6t@princeton.edu', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Multi-channelled mobile capacity', 'M', 'Hazel', 'http://dummyimage.com/156x100.png/5fa2dd/ffffff', 'hgrouse6u@biglobe.ne.jp', 1);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Synergistic directional attitude', 'F', 'Lonnie', 'http://dummyimage.com/127x100.png/cc0000/ffffff', 'ldecastri6v@nasa.gov', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Horizontal mission-critical service-desk', 'F', 'Angelina', 'http://dummyimage.com/149x100.png/cc0000/ffffff', 'ahasluck6w@usatoday.com', 2);
insert into user (description, gender, name, profile_image_path, social_id, social_type) values ('Right-sized reciprocal encryption', 'M', 'Wendel', 'http://dummyimage.com/132x100.png/cc0000/ffffff', 'wmulhall6x@mtv.com', 2);

insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (0, 1, 280);
insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (1, 1, 2);
insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (1, 1, 3);
insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (1, 1, 4);
insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (1, 1, 5);
insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (1, 1, 6);

insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (0, 2, 7);
insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (1, 2, 8);
insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (1, 2, 9);
insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (1, 2, 10);
insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (1, 2, 11);
insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (1, 2, 12);

insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (0, 3, 13);
insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (1, 3, 14);
insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (1, 3, 15);
insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (1, 3, 16);
insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (1, 3, 17);
insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (1, 3, 18);

insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (0, 4, 19);
insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (1, 4, 20);
insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (1, 4, 21);
insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (1, 4, 22);
insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (1, 4, 23);
insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (1, 4, 24);

# 남자 풀
insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (0, 5, 25);
insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (1, 5, 26);
insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (1, 5, 27);
insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (1, 5, 28);

# 여자 풀
insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (0, 6, 29);
insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (1, 6, 30);
insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (1, 6, 31);
insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (1, 6, 32);

insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (0, 7, 33);
insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (0, 8, 34);

insert into waiting_room_user_relation(type, user_id, waiting_room_id) values (2, 54, 7);
insert into waiting_room_user_relation(type, user_id, waiting_room_id) values (2, 134, 8);
insert into waiting_room_user_relation(type, user_id, waiting_room_id) values (2, 91, 6);
insert into waiting_room_user_relation(type, user_id, waiting_room_id) values (2, 169, 6);
insert into waiting_room_user_relation(type, user_id, waiting_room_id) values (2, 179, 6);
insert into waiting_room_user_relation(type, user_id, waiting_room_id) values (2, 92, 5);
insert into waiting_room_user_relation(type, user_id, waiting_room_id) values (2, 117, 6);
insert into waiting_room_user_relation(type, user_id, waiting_room_id) values (2, 173, 6);
insert into waiting_room_user_relation(type, user_id, waiting_room_id) values (2, 76, 7);
insert into waiting_room_user_relation(type, user_id, waiting_room_id) values (2, 192, 8);
insert into waiting_room_user_relation(type, user_id, waiting_room_id) values (2, 104, 7);
insert into waiting_room_user_relation(type, user_id, waiting_room_id) values (2, 57, 8);
insert into waiting_room_user_relation(type, user_id, waiting_room_id) values (2, 35, 7);
insert into waiting_room_user_relation(type, user_id, waiting_room_id) values (2, 54, 8);
insert into waiting_room_user_relation(type, user_id, waiting_room_id) values (2, 113, 5);
insert into waiting_room_user_relation(type, user_id, waiting_room_id) values (2, 74, 6);
insert into waiting_room_user_relation(type, user_id, waiting_room_id) values (2, 184, 7);
insert into waiting_room_user_relation(type, user_id, waiting_room_id) values (2, 39, 7);
insert into waiting_room_user_relation(type, user_id, waiting_room_id) values (2, 195, 8);
insert into waiting_room_user_relation(type, user_id, waiting_room_id) values (2, 124, 7);

insert into chatting_room (room_id, type) values (1, 2);
insert into chatting_room (room_id, type) values (2, 2);
insert into chatting_room (room_id, type) values (3, 2);
insert into chatting_room (room_id, type) values (4, 2);
insert into chatting_room (room_id, type) values (5, 2);
insert into chatting_room (room_id, type) values (6, 2);
insert into chatting_room (room_id, type) values (7, 2);
insert into chatting_room (room_id, type) values (8, 2);

insert into chatting_room (room_id, type) values (3, 0);
insert into chatting_room (room_id, type) values (3, 1);
insert into chatting_room (room_id, type) values (5, 0);
insert into chatting_room (room_id, type) values (5, 1);
insert into chatting_room (room_id, type) values (7, 0);
insert into chatting_room (room_id, type) values (7, 1);

insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (0, 5, 25);
insert into waiting_room_user_relation(type, waiting_room_id, user_id) values (0, 6, 29);

insert into profile(image_path, name) values ("profile01.png", "프로필 1");
insert into profile(image_path, name) values ("profile02.png", "프로필 2");
insert into profile(image_path, name) values ("profile03.png", "프로필 3");
insert into profile(image_path, name) values ("profile04.png", "프로필 4");
insert into profile(image_path, name) values ("profile05.png", "프로필 5");
insert into profile(image_path, name) values ("profile06.png", "프로필 6");
insert into profile(image_path, name) values ("profile07.png", "프로필 7");
insert into profile(image_path, name) values ("profile08.png", "프로필 8");
insert into profile(image_path, name) values ("profile09.png", "프로필 9");
insert into profile(image_path, name) values ("profile10.png", "프로필 10");